In [2]:
import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv(
  "vgsales.csv"
)

df.head(5)

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37

In [3]:
df.shape
# df.columns

(16598, 11)

In [4]:
df.describe()

,Rank,Year,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
count,16598.000000,16327.000000,16598.000000,16598.000000,16598.000000,16598.000000,16598.000000
mean,8300.605254,2006.406443,0.264667,0.146652,0.077782,0.048063,0.537441
std,4791.853933,5.828981,0.816683,0.505351,0.309291,0.188588,1.555028
min,1.000000,1980.000000,0.000000,0.000000,0.000000,0.000000,0.010000
25%,4151.250000,2003.000000,0.000000,0.000000,0.000000,0.000000,0.060000
50%,8300.500000,2007.000000,0.080000,0.020000,0.000000,0.010000,0.170000
75%,12449.750000,2010.000000,0.240000,0.110000,0.040000,0.040000,0.470000
max,16600.000000,2020.000000,41.490000,29.020000,10.220000,10.570000,82.740000

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 16598 entries, 0 to 16597
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Rank          16598 non-null  int64
 1   Name          16598 non-null  str
 2   Platform      16598 non-null  str
 3   Year          16327 non-null  float64
 4   Genre         16598 non-null  str
 5   Publisher     16540 non-null  str
 6   NA_Sales      16598 non-null  float64
 7   EU_Sales      16598 non-null  float64
 8   JP_Sales      16598 non-null  float64
 9   Other_Sales   16598 non-null  float64
 10  Global_Sales  16598 non-null  float64
dtypes: float64(6), int64(1), str(4)
memory usage: 1.4 MB

In [6]:
df.isna().sum()

Rank              0
Name              0
Platform          0
Year            271
Genre             0
Publisher        58
NA_Sales          0
EU_Sales          0
JP_Sales          0
Other_Sales       0
Global_Sales      0
dtype: int64

In [7]:
nameList= df["Year"].isna() & df["Name"].str.contains(r"\d{4}",regex=True)  
years= df.loc[nameList ,"Name"].str.extract(r"(\d{4})",expand=False)

df["Year"] = df["Year"].fillna(years).astype("float64")

df.isna().sum()
# df["Year"].dtype

Rank              0
Name              0
Platform          0
Year            254
Genre             0
Publisher        58
NA_Sales          0
EU_Sales          0
JP_Sales          0
Other_Sales       0
Global_Sales      0
dtype: int64

In [8]:
df["Year"].mean()#2006
df["Year"].median()#2007

np.float64(2007.0)

In [9]:
df["Publisher"].value_counts().head(25)

Publisher
Electronic Arts                           1351
Activision                                 975
Namco Bandai Games                         932
Ubisoft                                    921
Konami Digital Entertainment               832
THQ                                        715
Nintendo                                   703
Sony Computer Entertainment                683
Sega                                       639
Take-Two Interactive                       413
Capcom                                     381
Atari                                      363
Tecmo Koei                                 338
Square Enix                                233
Warner Bros. Interactive Entertainment     232
Disney Interactive Studios                 218
Unknown                                    203
Eidos Interactive                          198
Midway Games                               198
505 Games                                  192
Microsoft Game Studios                     189
Acclaim Entertainment                      184
D3Publisher                                184
Vivendi Games                              164
Codemasters                                152
Name: count, dtype: int64

In [10]:
mask= (df.groupby(["Name", "Platform"])["Publisher"].transform("count") == 1)&(df["Publisher"].isna())
       

df.loc[mask, "Publisher"] = df.groupby(["Name", "Platform"])["Publisher"].transform("first")
df["Publisher"].isna().sum()

np.int64(57)

In [11]:
df.groupby("Name")["Publisher"].transform("count")
 

mask= df["Name"].isin(df.loc[df["Publisher"].isna() ,"Name"]) 
yy= df.loc[mask ,["Name","Platform","Publisher"]]

cc =(df.groupby("Name")["Publisher"].transform("count") == 1) & (df["Publisher"].isna())

yy.groupby("Name")["Publisher"].unique()
cc
# kk =df.loc[cc , ["Name", "Platform", "Publisher"]]
# kk["PublisherNan"] =df.groupby("Name")["Publisher"].transform("first")
# kk
df.loc[cc,"Publisher"] =df.groupby("Name")["Publisher"].transform("first")
df.isna().sum()

Rank              0
Name              0
Platform          0
Year            254
Genre             0
Publisher        52
NA_Sales          0
EU_Sales          0
JP_Sales          0
Other_Sales       0
Global_Sales      0
dtype: int64

In [12]:
mask =  (
  (df.groupby("Name")["Name"].transform("count")> 1)  & (df["Publisher"].isna())
)

df.loc[mask,["Name","Publisher", "Platform", "Genre","Year"]]

adays=df[df["Name"].isin(df.loc[mask,"Name"])]

adays.groupby("Name")["Publisher"].unique()

gg=adays.groupby("Name")["Publisher"].nunique() ==1

gg[gg].index
uniq_mask=(df["Name"].isin(gg[gg].index)) & (df["Publisher"].isna())
df.loc[uniq_mask ,["Publisher"]] =df.groupby("Name")["Publisher"].transform("first")
df.isna().sum()

Rank              0
Name              0
Platform          0
Year            254
Genre             0
Publisher        51
NA_Sales          0
EU_Sales          0
JP_Sales          0
Other_Sales       0
Global_Sales      0
dtype: int64

In [14]:
df.loc[df["Publisher"].isna(),["Name","Platform" ,"Year","Genre"]]

,Name,Platform,Year,Genre
470,wwe Smackdown vs. Raw 2006,PS2,2006.0,Fighting
1303,Triple Play 99,PS,NaN,Sports
1662,Shrek / Shrek 2 2-in-1 Gameboy Advance Video,GBA,2007.0,Misc
2222,Bentley's Hackpack,GBA,2005.0,Misc
3159,Nicktoons Collection: Game Boy Advance Video V...,GBA,2004.0,Misc
3166,SpongeBob SquarePants: Game Boy Advance Video ...,GBA,2004.0,Misc
3766,SpongeBob SquarePants: Game Boy Advance Video ...,GBA,2004.0,Misc
4526,The Fairly Odd Parents: Game Boy Advance Video...,GBA,2004.0,Misc
4635,The Fairly Odd Parents: Game Boy Advance Video...,GBA,2004.0,Misc
5302,Dragon Ball Z: Budokai Tenkaichi 2 (JP sales),Wii,NaN,Action
5647,Cartoon Network Collection: Game Boy Advance V...,GBA,2005.0,Misc
6272,The Legend of Zelda: The Minish Cap(weekly JP ...,GBA,NaN,Action
6437,Sonic X: Game Boy Advance Video Volume 1,GBA,2004.0,Misc
6562,Dora the Explorer: Game Boy Advance Video Volu...,GBA,2004.0,Misc
6648,Cartoon Network Collection: Game Boy Advance V...,GBA,2004.0,Misc
6849,All Grown Up!: Game Boy Advance Video Volume 1,GBA,2004.0,Misc
7208,Nicktoons Collection: Game Boy Advance Video V...,GBA,2004.0,Misc
7351,Yu Yu Hakusho: Dark Tournament,PS2,NaN,Fighting
7470,SpongeBob SquarePants: Game Boy Advance Video ...,GBA,2004.0,Misc
7953,Thomas the Tank Engine & Friends,GBA,2004.0,Adventure
8330,Dragon Ball GT: Game Boy Advance Video Volume 1,GBA,2004.0,Misc
8341,Codename: Kids Next Door: Game Boy Advance Vid...,GBA,2004.0,Misc
8368,Teenage Mutant Ninja Turtles: Game Boy Advance...,GBA,2004.0,Misc
8503,Stronghold 3,PC,2011.0,Strategy
8770,Cartoon Network Collection: Game Boy Advance V...,GBA,2005.0,Misc
8848,Pokémon: Johto Photo Finish: Game Boy Advance ...,GBA,2004.0,Misc
8896,Strawberry Shortcake: Game Boy Advance Video V...,GBA,2004.0,Misc
9517,Farming Simulator 2011,PC,2010.0,Simulation
9749,Super Robot Wars OG Saga: Masou Kishin II - Re...,PSP,NaN,Strategy
10382,Disney Channel Collection Vol. 1,GBA,2004.0,Misc
10494,Atsumare! Power Pro Kun no DS Koushien,DS,NaN,Sports
11076,Action Man-Operation Extreme,PS,NaN,Action
11526,Cartoon Network Collection: Game Boy Advance V...,GBA,2004.0,Misc
12487,Chou Soujuu Mecha MG,DS,NaN,Simulation
12517,Prinny: Can I Really Be The Hero? (US sales),PSP,NaN,Action
13672,B.L.U.E.: Legend of Water,PS,NaN,Adventure
14087,Housekeeping,DS,NaN,Action
14296,Bikkuriman Daijiten,DS,NaN,Misc
14311,Silverlicious,DS,2012.0,Action
14698,UK Truck Simulator,PC,2010.0,Simulation
14942,Umineko no Naku Koro ni San: Shinjitsu to Gens...,PS3,NaN,Adventure
15056,Xia-Xia,DS,2012.0,Platform
15325,Nicktoons Collection: Game Boy Advance Video V...,GBA,2005.0,Misc
15353,Demolition Company: Gold Edition,PC,2011.0,Simulation
15788,"Moshi, Kono Sekai ni Kami-sama ga Iru to suru ...",PSV,2016.0,Adventure
15915,Dream Dancer,DS,NaN,Misc
16191,Homeworld Remastered Collection,PC,NaN,Strategy
16208,Super Robot Monkey Team: Game Boy Advance Vide...,GBA,2005.0,Misc
16367,Dance with Devils,PSV,2016.0,Action
16494,Legends of Oz: Dorothy's Return,3DS,2014.0,Puzzle
16543,Driving Simulator 2011,PC,2011.0,Racing

In [16]:
missing_names = df.loc[df["Publisher"].isna(), "Name"].unique()

adays = df[df["Name"].isin(missing_names)]

adays[["Name", "Platform", "Year", "Publisher"]].sort_values("Name")

,Name,Platform,Year,Publisher
11076,Action Man-Operation Extreme,PS,NaN,NaN
6849,All Grown Up!: Game Boy Advance Video Volume 1,GBA,2004.0,NaN
10494,Atsumare! Power Pro Kun no DS Koushien,DS,NaN,NaN
13672,B.L.U.E.: Legend of Water,PS,NaN,NaN
2222,Bentley's Hackpack,GBA,2005.0,NaN
14296,Bikkuriman Daijiten,DS,NaN,NaN
5647,Cartoon Network Collection: Game Boy Advance V...,GBA,2005.0,NaN
8770,Cartoon Network Collection: Game Boy Advance V...,GBA,2005.0,NaN
6648,Cartoon Network Collection: Game Boy Advance V...,GBA,2004.0,NaN
11526,Cartoon Network Collection: Game Boy Advance V...,GBA,2004.0,NaN
12487,Chou Soujuu Mecha MG,DS,NaN,NaN
8341,Codename: Kids Next Door: Game Boy Advance Vid...,GBA,2004.0,NaN
16367,Dance with Devils,PSV,2016.0,NaN
15353,Demolition Company: Gold Edition,PC,2011.0,NaN
10382,Disney Channel Collection Vol. 1,GBA,2004.0,NaN
6562,Dora the Explorer: Game Boy Advance Video Volu...,GBA,2004.0,NaN
8330,Dragon Ball GT: Game Boy Advance Video Volume 1,GBA,2004.0,NaN
5302,Dragon Ball Z: Budokai Tenkaichi 2 (JP sales),Wii,NaN,NaN
15915,Dream Dancer,DS,NaN,NaN
16543,Driving Simulator 2011,PC,2011.0,NaN
9517,Farming Simulator 2011,PC,2010.0,NaN
16191,Homeworld Remastered Collection,PC,NaN,NaN
14087,Housekeeping,DS,NaN,NaN
16494,Legends of Oz: Dorothy's Return,3DS,2014.0,NaN
15788,"Moshi, Kono Sekai ni Kami-sama ga Iru to suru ...",PSV,2016.0,NaN
3159,Nicktoons Collection: Game Boy Advance Video V...,GBA,2004.0,NaN
7208,Nicktoons Collection: Game Boy Advance Video V...,GBA,2004.0,NaN
15325,Nicktoons Collection: Game Boy Advance Video V...,GBA,2005.0,NaN
8848,Pokémon: Johto Photo Finish: Game Boy Advance ...,GBA,2004.0,NaN
12517,Prinny: Can I Really Be The Hero? (US sales),PSP,NaN,NaN
1662,Shrek / Shrek 2 2-in-1 Gameboy Advance Video,GBA,2007.0,NaN
14311,Silverlicious,DS,2012.0,NaN
6437,Sonic X: Game Boy Advance Video Volume 1,GBA,2004.0,NaN
3166,SpongeBob SquarePants: Game Boy Advance Video ...,GBA,2004.0,NaN
3766,SpongeBob SquarePants: Game Boy Advance Video ...,GBA,2004.0,NaN
7470,SpongeBob SquarePants: Game Boy Advance Video ...,GBA,2004.0,NaN
8896,Strawberry Shortcake: Game Boy Advance Video V...,GBA,2004.0,NaN
8503,Stronghold 3,PC,2011.0,NaN
16208,Super Robot Monkey Team: Game Boy Advance Vide...,GBA,2005.0,NaN
9749,Super Robot Wars OG Saga: Masou Kishin II - Re...,PSP,NaN,NaN
8368,Teenage Mutant Ninja Turtles: Game Boy Advance...,GBA,2004.0,NaN
4526,The Fairly Odd Parents: Game Boy Advance Video...,GBA,2004.0,NaN
4635,The Fairly Odd Parents: Game Boy Advance Video...,GBA,2004.0,NaN
6272,The Legend of Zelda: The Minish Cap(weekly JP ...,GBA,NaN,NaN
7953,Thomas the Tank Engine & Friends,GBA,2004.0,NaN
1303,Triple Play 99,PS,NaN,NaN
14698,UK Truck Simulator,PC,2010.0,NaN
14942,Umineko no Naku Koro ni San: Shinjitsu to Gens...,PS3,NaN,NaN
15056,Xia-Xia,DS,2012.0,NaN
7351,Yu Yu Hakusho: Dark Tournament,PS2,NaN,NaN
470,wwe Smackdown vs. Raw 2006,PS2,2006.0,NaN

In [18]:
publisher_counts = adays.groupby("Name")["Publisher"].nunique()

safe_names = publisher_counts[publisher_counts == 1].index

print("Tek bir Publisher bulunan isim sayısı:", len(safe_names))
print(safe_names.tolist())

Tek bir Publisher bulunan isim sayısı: 0
[]

In [21]:
print("Eksik Publisher olan benzersiz isim:", len(missing_names))
print("adays satır sayısı:", len(adays))
print("Dolu Publisher sayısı:", adays["Publisher"].notna().sum())

Eksik Publisher olan benzersiz isim: 51
adays satır sayısı: 51
Dolu Publisher sayısı: 0

In [23]:
print("Eksik Publisher:", df["Publisher"].isna().sum())
print("Eksik Year:", df["Year"].isna().sum())

Eksik Publisher: 51
Eksik Year: 254

In [25]:
missing_years = df.loc[
    df["Year"].isna(),
    ["Name", "Platform", "Genre", "Publisher"]
]

print("Eksik Year satırı:", len(missing_years))
print("Benzersiz oyun adı:", missing_years["Name"].nunique())

missing_years.head(15)

Eksik Year satırı: 254
Benzersiz oyun adı: 219

,Name,Platform,Genre,Publisher
431,LEGO Batman: The Videogame,Wii,Action,Warner Bros. Interactive Entertainment
607,Space Invaders,2600,Shooter,Atari
624,Rock Band,X360,Misc,Electronic Arts
649,Frogger's Adventures: Temple of the Frog,GBA,Adventure,Konami Digital Entertainment
652,LEGO Indiana Jones: The Original Adventures,Wii,Action,LucasArts
711,Call of Duty 3,Wii,Shooter,Activision
782,Rock Band,Wii,Misc,MTV Games
1126,Call of Duty: Black Ops,PC,Shooter,Activision
1133,Rock Band,PS3,Misc,Electronic Arts
1303,Triple Play 99,PS,Sports,NaN
1433,LEGO Harry Potter: Years 5-7,Wii,Action,Warner Bros. Interactive Entertainment
1498,LEGO Batman: The Videogame,PSP,Action,Warner Bros. Interactive Entertainment
1513,Adventure,2600,Adventure,Atari
1585,Combat,2600,Action,Atari
1697,Hitman 2: Silent Assassin,XB,Action,Eidos Interactive

In [27]:
missing_names = df.loc[df["Year"].isna(), "Name"].unique()

year_info = (
    df[df["Name"].isin(missing_names)]
    .groupby("Name")["Year"]
    .agg(["count", "nunique", "unique"])
)

candidates = year_info[
    (year_info["count"] > 0) &
    (year_info["nunique"] == 1)
]

print("Araştırmaya değer oyun sayısı:", len(candidates))
print(candidates)

Araştırmaya değer oyun sayısı: 81
                                        count  nunique         unique
Name
AKB1/48: Idol to Guam de Koishitara...      1        1  [2011.0, nan]
Aquaman: Battle for Atlantis                1        1  [nan, 2003.0]
Battle vs. Chess                            1        1  [nan, 2011.0]
Bejeweled 3                                 1        1  [nan, 2010.0]
BioShock 2                                  2        1  [2010.0, nan]
...                                       ...      ...            ...
WCW Backstage Assault                       1        1  [1999.0, nan]
WRC: FIA World Rally Championship           1        1  [nan, 2005.0]
Wet                                         1        1  [2009.0, nan]
Without Warning                             1        1  [2005.0, nan]
World of Tanks                              1        1  [2011.0, nan]

[81 rows x 3 columns]

In [29]:
candidate_names = candidates.index

candidate_rows = df.loc[
    df["Name"].isin(candidate_names),
    ["Name", "Platform", "Year", "Genre", "Publisher"]
].sort_values(["Name", "Platform"])

candidate_rows

,Name,Platform,Year,Genre,Publisher
4825,AKB1/48: Idol to Guam de Koishitara...,PSP,2011.0,Misc,Namco Bandai Games
16198,AKB1/48: Idol to Guam de Koishitara...,X360,NaN,Misc,Namco Bandai Games
16249,Aquaman: Battle for Atlantis,GC,2003.0,Action,TDK Mediactive
16065,Aquaman: Battle for Atlantis,XB,NaN,Action,Unknown
14583,Battle vs. Chess,PC,NaN,Misc,TopWare Interactive
...,...,...,...,...,...
3952,Wet,X360,NaN,Shooter,Bethesda Softworks
13998,Without Warning,PS2,2005.0,Shooter,Capcom
15717,Without Warning,XB,NaN,Shooter,Capcom
6032,World of Tanks,PC,2011.0,Shooter,Wargaming.net
13962,World of Tanks,X360,NaN,Shooter,Wargaming.net

In [31]:
platform_year_counts = (
    df.groupby(["Name", "Platform"])["Year"]
    .count()
)

print("Yılı bilinen Name + Platform grubu sayısı:",
      (platform_year_counts > 0).sum())

Yılı bilinen Name + Platform grubu sayısı: 16341

In [36]:
group = df.groupby(["Name", "Platform"])["Year"]

year_count = group.transform("count")
year_nunique = group.transform("nunique")
year_first = group.transform("first")

mask = (
    df["Year"].isna()
    & (year_count > 0)
    & (year_nunique == 1)
)

print("Güvenilir eşleşme adayı:", mask.sum())

df.loc[mask, ["Name", "Platform", "Year"]].head(20)
df.loc[mask, "Year"] = year_first[mask] 
df.loc[
    df["Name"].eq("Sonic the Hedgehog"),
    ["Name", "Platform", "Year"]
]

Güvenilir eşleşme adayı: 0

                    Name Platform    Year
254   Sonic the Hedgehog      GEN  1991.0
1715  Sonic the Hedgehog      PS3  2006.0
1983  Sonic the Hedgehog     X360  2006.0
4145  Sonic the Hedgehog      PS3  2006.0

In [38]:
missing_names = df.loc[df["Year"].isna(), "Name"].unique()

year_info = (
    df[df["Name"].isin(missing_names)]
    .groupby("Name")["Year"]
    .agg(["count", "nunique", "unique"])
)

cross_platform_candidates = year_info[
    (year_info["count"] > 0) &
    (year_info["nunique"] == 1)
]

print("Farklı platformlardan araştırılacak oyun sayısı:",
      len(cross_platform_candidates))

Farklı platformlardan araştırılacak oyun sayısı: 81

In [39]:
missing_names = df.loc[df["Year"].isna(), "Name"].unique()

cross_platform = df[df["Name"].isin(missing_names)]

cross_platform_summary = (
    cross_platform.groupby("Name")
    .agg(
        Platforms=("Platform", lambda x: list(x)),
        Years=("Year", lambda x: list(x)),
        Publishers=("Publisher", lambda x: list(x))
    )
)

cross_platform_summary.loc[
    cross_platform_summary.index.isin(cross_platform_candidates.index)
].head(20)

,Platforms,Years,Publishers
Name,,,
AKB1/48: Idol to Guam de Koishitara...,"[PSP, X360]","[2011.0, nan]","[Namco Bandai Games, Namco Bandai Games]"
Aquaman: Battle for Atlantis,"[XB, GC]","[nan, 2003.0]","[Unknown, TDK Mediactive]"
Battle vs. Chess,"[PS3, X360, PC]","[nan, 2011.0, nan]","[TopWare Interactive, TopWare Interactive, Top..."
Bejeweled 3,"[DS, PS3, X360, PC]","[nan, nan, nan, 2010.0]","[Unknown, Unknown, Unknown, PopCap Games]"
BioShock 2,"[X360, PS3, PC]","[2010.0, 2010.0, nan]","[Take-Two Interactive, Take-Two Interactive, T..."
Brothers in Arms: Furious 4,"[PS3, X360]","[2012.0, nan]","[Ubisoft, Ubisoft]"
Cabela's Alaskan Adventure,"[X360, PS2]","[2006.0, nan]","[Activision, Unknown]"
Call of Duty 3,"[X360, Wii, PS3, PS2]","[2006.0, nan, 2006.0, 2006.0]","[Activision, Activision, Activision, Activision]"
Call of Duty: Black Ops,"[X360, PS3, PC, Wii, DS]","[2010.0, 2010.0, nan, 2010.0, 2010.0]","[Activision, Activision, Activision, Activisio..."
Captain America: Super Soldier,"[PS3, X360, 3DS, Wii, DS]","[2011.0, 2011.0, 2011.0, nan, nan]","[Sega, Sega, Sega, Sega, Sega]"
Custom Robo,"[GC, N64]","[2004.0, nan]","[Nintendo, Nintendo]"
Dance! It's Your Stage,"[PS3, Wii]","[2011.0, nan]","[DTP Entertainment, DTP Entertainment]"
Danganronpa: Trigger Happy Havoc,"[PSV, PSP]","[2013.0, nan]","[Nippon Ichi Software, Unknown]"
Dead Island: Riptide,"[X360, PS3, PC]","[2013.0, 2013.0, nan]","[Deep Silver, Deep Silver, Deep Silver]"
Dead Space 3,"[PS3, X360, PC]","[2013.0, 2013.0, nan]","[Electronic Arts, Electronic Arts, Electronic ..."
Def Jam: Fight for NY,"[PS2, XB, GC]","[2004.0, nan, 2004.0]","[Electronic Arts, Electronic Arts, Electronic ..."
Dinotopia: The Sunstone Odyssey,"[GC, XB]","[nan, 2003.0]","[Unknown, TDK Mediactive]"
Disney's Chicken Little: Ace In Action,"[Wii, DS]","[nan, 2006.0]","[Disney Interactive Studios, Disney Interactiv..."
Final Fantasy XI,"[PS2, X360]","[nan, 2006.0]","[Unknown, Square Enix]"
Freaky Flyers,"[PS2, XB, GC]","[2003.0, 2003.0, nan]","[Midway Games, Midway Games, Unknown]"